# -*- coding: utf-8 -*-
"""phi35_bpo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P6r5Mpso8tLhYqJrS4A45lrd-QZCzJtO
"""

!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install peft accelerate bitsandbytes  # no trl pin - let unsloth control it

import torch
from datasets import load_dataset
from unsloth import FastLanguageModel
from trl import SFTTrainer
from transformers import TrainingArguments

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name      = "unsloth/Phi-3.5-mini-instruct",
    max_seq_length  = 2048,
    load_in_4bit    = True,   # saves memory on Colab
)

model = FastLanguageModel.get_peft_model(
    model,
    r                       = 16,
    target_modules          = ["q_proj", "k_proj", "v_proj", "o_proj",
                               "gate_proj", "up_proj", "down_proj"],
    lora_alpha              = 16,
    lora_dropout            = 0,
    bias                    = "none",
    use_gradient_checkpointing = "unsloth",
    random_state            = 3407,
)

# Load the zai-org/BPO dataset (train split)
dataset = load_dataset("zai-org/BPO", split="train")

def formatting_prompts_func(examples):
    instructions = examples["prompt"]           # original / weak prompt
    responses    = examples["optimized_prompt"] # optimized target prompt
    texts = []
    for instruction, response in zip(instructions, responses):
        text = f"<|user|>\nOptimize this prompt: {instruction}<|end|>\n<|assistant|>\n{response}<|end|>"
        texts.append(text)
    return {"text": texts}

dataset = dataset.map(formatting_prompts_func, batched=True)

import trl
print(trl.__version__)

args = TrainingArguments(
    output_dir="phi35_bpo_outputs",
    per_device_train_batch_size=2,
    gradient_accumulation_steps=4,
    warmup_steps=10,
    max_steps=100,
    learning_rate=2e-4,
    logging_steps=1,
    optim="adamw_8bit",
    weight_decay=0.01,
    lr_scheduler_type="linear",
    seed=3407,
)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=2048,
    args=args,
)
trainer.train()

FastLanguageModel.for_inference(model)

inputs = tokenizer(
    ["<|user|>\nOptimize this prompt: Explain gravity.<|end|>\n<|assistant|>\n"],
    return_tensors="pt"
).to("cuda")

outputs = model.generate(**inputs, max_new_tokens=128, repetition_penalty=1.15)
print(tokenizer.batch_decode(outputs, skip_special_tokens=True)[0])