# -*- coding: utf-8 -*-
"""revised_bpo.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1P6r5Mpso8tLhYqJrS4A45lrd-QZCzJtO
"""

!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install peft accelerate bitsandbytes  # no trl pin - let unsloth control it

import torch
from datasets import load_dataset
from unsloth import FastLanguageModel
from trl import SFTTrainer
from transformers import TrainingArguments

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/SmolLM2-360M-Instruct",
    max_seq_length=1024,
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=3407,
)

# --- Load and format BPO dataset (SmolLM uses ChatML format) ---
dataset = load_dataset("zai-org/BPO", split="train")

def formatting_prompts_func(examples):
    instructions = examples["prompt"]
    responses = examples["optimized_prompt"]
    texts = []
    for instruction, response in zip(instructions, responses):
        # SmolLM ChatML format: <|im_start|>role\ncontent<|im_end|>\n
        text = (
            "<|im_start|>system\n"
            "You rewrite user prompts to be clearer, more specific, and more likely to get good AI responses. Output only the rewritten prompt.<|im_end|>\n"
            "<|im_start|>user\n"
            f"Optimize this prompt: {instruction}<|im_end|>\n"
            "<|im_start|>assistant\n"
            f"{response}<|im_end|>"
        )
        texts.append(text)
    return {"text": texts}

dataset = dataset.map(formatting_prompts_func, batched=True)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=1024,
    args=TrainingArguments(
        output_dir="smollm_bpo_outputs",
        per_device_train_batch_size=4,
        gradient_accumulation_steps=4,
        warmup_steps=10,
        max_steps=200,
        learning_rate=2e-4,
        logging_steps=1,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=3407,
    ),
)

trainer.train()

FastLanguageModel.for_inference(model)

text = "<|im_start|>system\nYou rewrite user prompts to be clearer and more specific. Output only the rewritten prompt.<|im_end|>\n<|im_start|>user\nOptimize this prompt: Explain gravity.<|im_end|>\n<|im_start|>assistant\n"
inputs = tokenizer(text, return_tensors="pt").to("cuda")
outputs = model.generate(**inputs, max_new_tokens=128, repetition_penalty=1.15, pad_token_id=tokenizer.eos_token_id)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

output_dir = "smollm_bpo_lora"
trainer.save_model(output_dir)
tokenizer.save_pretrained(output_dir)

!zip -r smollm_bpo_lora.zip smollm_bpo_lora
from google.colab import files
files.download("smollm_bpo_lora.zip")