# -*- coding: utf-8 -*-
"""ranked_prompt.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-hG39bBdFUNIbhMbt7a2y8OIkYFDUDxl
"""

!pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
!pip install peft accelerate bitsandbytes  # no trl pin - let unsloth control it

import torch
from datasets import load_dataset
from unsloth import FastLanguageModel
from trl import SFTTrainer
from transformers import TrainingArguments

model, tokenizer = FastLanguageModel.from_pretrained(
    model_name="unsloth/SmolLM2-360M-Instruct",
    max_seq_length=1024,
    load_in_4bit=True,
)

model = FastLanguageModel.get_peft_model(
    model,
    r=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha=16,
    lora_dropout=0,
    bias="none",
    use_gradient_checkpointing="unsloth",
    random_state=3407,
)

dataset = load_dataset("data-is-better-together/10k_prompts_ranked", split="train")

def formatting_ranked_func(examples):
    """Format each prompt + avg_rating as a ChatML dialogue.

    We train the model to act as a prompt-quality rater that outputs a
    single number between 1 and 5 (float with 1 decimal) for each prompt.
    """
    prompts = examples["prompt"]
    avg_ratings = examples["avg_rating"]

    texts = []
    for prompt, rating in zip(prompts, avg_ratings):
        if rating is None:
            # Skip examples without a valid rating
            continue

        # Round to one decimal place to keep targets simple and consistent.
        score = round(float(rating), 1)
        # Ensure score stays within [1, 5]
        score = max(1.0, min(5.0, score))

        # SmolLM ChatML format: <|im_start|>role\ncontent<|im_end|>\n
        text = (
            "<|im_start|>system\n"
            "You are an expert prompt-quality rater. "
            "Given a user prompt, you output a single quality score between 1 and 5, "
            "where 1 is very poor and 5 is excellent. "
            "Respond ONLY with the numeric score (e.g., 3.8), no explanation.\n"
            "<|im_end|>\n"
            "<|im_start|>user\n"
            f"Rate the quality of this prompt on a 1 to 5 scale: {prompt}\n"
            "<|im_end|>\n"
            "<|im_start|>assistant\n"
            f"{score}<|im_end|>"
        )
        texts.append(text)

    return {"text": texts}


dataset = dataset.map(formatting_ranked_func, batched=True, remove_columns=dataset.column_names)

trainer = SFTTrainer(
    model=model,
    tokenizer=tokenizer,
    train_dataset=dataset,
    dataset_text_field="text",
    max_seq_length=1024,
    args=TrainingArguments(
        output_dir="smollm_ranked_outputs",
        per_device_train_batch_size=4,
        gradient_accumulation_steps=4,
        warmup_steps=10,
        max_steps=200,
        learning_rate=2e-4,
        logging_steps=1,
        optim="adamw_8bit",
        weight_decay=0.01,
        lr_scheduler_type="linear",
        seed=3407,
    ),
)

trainer.train()

FastLanguageModel.for_inference(model)

test_prompt = "Summarize the key risks of deploying an LLM chatbot in healthcare."
text = (
    "<|im_start|>system\n"
    "You are an expert prompt-quality rater. "
    "Given a user prompt, you output a single quality score between 1 and 5, "
    "where 1 is very poor and 5 is excellent. "
    "Respond ONLY with the numeric score (e.g., 3.8), no explanation.\n"
    "<|im_end|>\n"
    "<|im_start|>user\n"
    f"Rate the quality of this prompt on a 1 to 5 scale: {test_prompt}\n"
    "<|im_end|>\n"
    "<|im_start|>assistant\n"
)
inputs = tokenizer(text, return_tensors="pt").to("cuda" if torch.cuda.is_available() else "cpu")
outputs = model.generate(
    **inputs,
    max_new_tokens=16,
    repetition_penalty=1.05,
    pad_token_id=tokenizer.eos_token_id,
)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

output_dir = "smollm_ranked_lora"
trainer.save_model(output_dir)
tokenizer.save_pretrained(output_dir)

!zip -r smollm_ranked_lora.zip smollm_ranked_lora
from google.colab import files

files.download("smollm_ranked_lora.zip")